### PR TITLE
Website refactor

### PR DESCRIPTION
**Pull request by wtrocki**

### CODE REVIEW

**Comment by wtrocki** [comment]
@RDrohan - There are couple issues with provided layout, but overall work looks great. 
I think that it's better to still allow people to write in standard makrdown - this will allow kids to contribute and we can teach them markdown. 

I will try to fix build and couple issues and update website.

**Comment by RDrohan** [comment]
Hi Wojciech,
Thanks for coming back to me quickly on this. Feel free to do whatever you think is best.

Regards,

Ricky

**Comment by wtrocki** [comment]
Hey.. changes require some improvement before merge. Lets talk about it

**Comment by RDrohan** [comment]
I've fixed the conflict but the Travis CI fails. If you want to let me know what has to be changed in order to fix it then let me know.

**Comment by wtrocki** [comment]
Archiving website. Domain may expire soon.

**Pull request closed without merging**
